<?php

namespace Flynt\CustomPostTypes;

function registerTeamMemberPostType()
{
    $labels = array(
        'name'                  => _x('Team Members', 'Team Member General Name', 'flynt'),
        'singular_name'         => _x('Team Member', 'Team Member Singular Name', 'flynt'),
        'menu_name'             => __('Team', 'flynt'),
        'name_admin_bar'        => __('Team Member', 'flynt'),
        'all_items'             => __('All Team Members', 'flynt'),
        'add_new_item'          => __('Add New Team Member', 'flynt'),
        'add_new'               => __('Add New', 'flynt'),
        'new_item'              => __('New Team Member', 'flynt'),
        'edit_item'             => __('Edit Team Member', 'flynt'),
        'update_item'           => __('Update Team Member', 'flynt'),
        'view_item'             => __('View Team Member', 'flynt'),
        'view_items'            => __('View Team Members', 'flynt'),
        'search_items'          => __('Search Team Member', 'flynt'),
    );

    $args = array(
        'label'                 => __('Team Member', 'flynt'),
        'description'           => __('Team Member Description', 'flynt'),
        'labels'                => $labels,
        'supports'              => array('title'),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'rewrite'               => array( 'slug' => 'team-member', 'with_front' => false ),
        'capability_type'       => 'page',
        'menu_icon'             => 'dashicons-groups',
    );

    register_post_type('team-member', $args);
}

add_action('init', '\\Flynt\\CustomPostTypes\\registerTeamMemberPostType');

if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_5f7a88e1a55f5',
        'title' => 'Team Member Metabox',
        'fields' => array(
            array(
                'key' => 'field_5f7a88fd6df5e',
                'label' => 'Avatar',
                'name' => 'avatar',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f7a8912c2129',
                'label' => 'Role',
                'name' => 'role',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f7a8918c212a',
                'label' => 'LinkedIn Url',
                'name' => 'linkedin_url',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f7a892fc212b',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'default',
                'media_upload' => 0,
                'delay' => 1,
            ),
            array(
                'key' => 'field_5f7a8943c212c',
                'label' => 'Mention',
                'name' => 'mention',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'default',
                'media_upload' => 0,
                'delay' => 1,
            ),
            array(
                'key' => 'field_5f7a8961c212d',
                'label' => 'Contact Button Title',
                'name' => 'contact_button_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f7a896ec212e',
                'label' => 'Contact Button Link',
                'name' => 'contact_button_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'team-member',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
endif;
